/* eslint-disable default-case */
/* eslint-disable no-array-constructor */
const orderCards = (pile, cards, isCardFoundAt) => {
  const pileNumber = Number(pile)
  let tmp_cards = new Array();
  tmp_cards = [].concat(cards);
  switch (pileNumber) {
    case 0:
      switch (isCardFoundAt) {
        case "top":
          cards[0] = tmp_cards[0];
          cards[1] = tmp_cards[3];
          cards[2] = tmp_cards[6];
          cards[3] = tmp_cards[9];
          cards[4] = tmp_cards[12];
          cards[5] = tmp_cards[15];
          cards[6] = tmp_cards[18];
          cards[7] = tmp_cards[21];
          cards[8] = tmp_cards[24];
          cards[9] = tmp_cards[1];
          cards[10] = tmp_cards[4];
          cards[11] = tmp_cards[7];
          cards[12] = tmp_cards[10];
          cards[13] = tmp_cards[13];
          cards[14] = tmp_cards[16];
          cards[15] = tmp_cards[19];
          cards[16] = tmp_cards[22];
          cards[17] = tmp_cards[25];
          cards[18] = tmp_cards[2];
          cards[19] = tmp_cards[5];
          cards[20] = tmp_cards[8];
          cards[21] = tmp_cards[11];
          cards[22] = tmp_cards[14];
          cards[23] = tmp_cards[17];
          cards[24] = tmp_cards[20];
          cards[25] = tmp_cards[23];
          cards[26] = tmp_cards[26];
          break;
        case "middle":
          cards[0] = tmp_cards[1];
          cards[1] = tmp_cards[4];
          cards[2] = tmp_cards[7];
          cards[3] = tmp_cards[10];
          cards[4] = tmp_cards[13];
          cards[5] = tmp_cards[16];
          cards[6] = tmp_cards[19];
          cards[7] = tmp_cards[22];
          cards[8] = tmp_cards[25];
          cards[9] = tmp_cards[0];
          cards[10] = tmp_cards[3];
          cards[11] = tmp_cards[6];
          cards[12] = tmp_cards[9];
          cards[13] = tmp_cards[12];
          cards[14] = tmp_cards[15];
          cards[15] = tmp_cards[18];
          cards[16] = tmp_cards[21];
          cards[17] = tmp_cards[24];
          cards[18] = tmp_cards[2];
          cards[19] = tmp_cards[5];
          cards[20] = tmp_cards[8];
          cards[21] = tmp_cards[11];
          cards[22] = tmp_cards[14];
          cards[23] = tmp_cards[17];
          cards[24] = tmp_cards[20];
          cards[25] = tmp_cards[23];
          cards[26] = tmp_cards[26];
          break;
        case "bottom":
          cards[0] = tmp_cards[2];
          cards[1] = tmp_cards[5];
          cards[2] = tmp_cards[8];
          cards[3] = tmp_cards[11];
          cards[4] = tmp_cards[14];
          cards[5] = tmp_cards[17];
          cards[6] = tmp_cards[20];
          cards[7] = tmp_cards[23];
          cards[8] = tmp_cards[26];
          cards[9] = tmp_cards[1];
          cards[10] = tmp_cards[4];
          cards[11] = tmp_cards[7];
          cards[12] = tmp_cards[10];
          cards[13] = tmp_cards[13];
          cards[14] = tmp_cards[16];
          cards[15] = tmp_cards[19];
          cards[16] = tmp_cards[22];
          cards[17] = tmp_cards[25];
          cards[18] = tmp_cards[0];
          cards[19] = tmp_cards[3];
          cards[20] = tmp_cards[6];
          cards[21] = tmp_cards[9];
          cards[22] = tmp_cards[12];
          cards[23] = tmp_cards[15];
          cards[24] = tmp_cards[18];
          cards[25] = tmp_cards[21];
          cards[26] = tmp_cards[24];
          break;
      }
      break;
    case 1:
      switch (isCardFoundAt) {
        case "top":
          cards[0] = tmp_cards[1];
          cards[1] = tmp_cards[4];
          cards[2] = tmp_cards[7];
          cards[3] = tmp_cards[10];
          cards[4] = tmp_cards[13];
          cards[5] = tmp_cards[16];
          cards[6] = tmp_cards[19];
          cards[7] = tmp_cards[22];
          cards[8] = tmp_cards[25];
          cards[9] = tmp_cards[0];
          cards[10] = tmp_cards[3];
          cards[11] = tmp_cards[6];
          cards[12] = tmp_cards[9];
          cards[13] = tmp_cards[12];
          cards[14] = tmp_cards[15];
          cards[15] = tmp_cards[18];
          cards[16] = tmp_cards[21];
          cards[17] = tmp_cards[24];
          cards[18] = tmp_cards[2];
          cards[19] = tmp_cards[5];
          cards[20] = tmp_cards[8];
          cards[21] = tmp_cards[11];
          cards[22] = tmp_cards[14];
          cards[23] = tmp_cards[17];
          cards[24] = tmp_cards[20];
          cards[25] = tmp_cards[23];
          cards[26] = tmp_cards[26];
          break;
        case "middle":
          cards[0] = tmp_cards[0];
          cards[1] = tmp_cards[3];
          cards[2] = tmp_cards[6];
          cards[3] = tmp_cards[9];
          cards[4] = tmp_cards[12];
          cards[5] = tmp_cards[15];
          cards[6] = tmp_cards[18];
          cards[7] = tmp_cards[21];
          cards[8] = tmp_cards[24];
          cards[9] = tmp_cards[1];
          cards[10] = tmp_cards[4];
          cards[11] = tmp_cards[7];
          cards[12] = tmp_cards[10];
          cards[13] = tmp_cards[13];
          cards[14] = tmp_cards[16];
          cards[15] = tmp_cards[19];
          cards[16] = tmp_cards[22];
          cards[17] = tmp_cards[25];
          cards[18] = tmp_cards[2];
          cards[19] = tmp_cards[5];
          cards[20] = tmp_cards[8];
          cards[21] = tmp_cards[11];
          cards[22] = tmp_cards[14];
          cards[23] = tmp_cards[17];
          cards[24] = tmp_cards[20];
          cards[25] = tmp_cards[23];
          cards[26] = tmp_cards[26];
          break;
        case "bottom":
          cards[0] = tmp_cards[2];
          cards[1] = tmp_cards[5];
          cards[2] = tmp_cards[8];
          cards[3] = tmp_cards[11];
          cards[4] = tmp_cards[14];
          cards[5] = tmp_cards[17];
          cards[6] = tmp_cards[20];
          cards[7] = tmp_cards[23];
          cards[8] = tmp_cards[26];
          cards[9] = tmp_cards[0];
          cards[10] = tmp_cards[3];
          cards[11] = tmp_cards[6];
          cards[12] = tmp_cards[9];
          cards[13] = tmp_cards[12];
          cards[14] = tmp_cards[15];
          cards[15] = tmp_cards[18];
          cards[16] = tmp_cards[21];
          cards[17] = tmp_cards[24];
          cards[18] = tmp_cards[1];
          cards[19] = tmp_cards[4];
          cards[20] = tmp_cards[7];
          cards[21] = tmp_cards[10];
          cards[22] = tmp_cards[13];
          cards[23] = tmp_cards[16];
          cards[24] = tmp_cards[19];
          cards[25] = tmp_cards[22];
          cards[26] = tmp_cards[25];
          break;
      }
      break;
    case 2:
      switch (isCardFoundAt) {
        case "top":
          cards[0] = tmp_cards[2];
          cards[1] = tmp_cards[5];
          cards[2] = tmp_cards[8];
          cards[3] = tmp_cards[11];
          cards[4] = tmp_cards[14];
          cards[5] = tmp_cards[17];
          cards[6] = tmp_cards[20];
          cards[7] = tmp_cards[23];
          cards[8] = tmp_cards[26];
          cards[9] = tmp_cards[1];
          cards[10] = tmp_cards[4];
          cards[11] = tmp_cards[7];
          cards[12] = tmp_cards[10];
          cards[13] = tmp_cards[13];
          cards[14] = tmp_cards[16];
          cards[15] = tmp_cards[19];
          cards[16] = tmp_cards[22];
          cards[17] = tmp_cards[25];
          cards[18] = tmp_cards[0];
          cards[19] = tmp_cards[3];
          cards[20] = tmp_cards[6];
          cards[21] = tmp_cards[9];
          cards[22] = tmp_cards[12];
          cards[23] = tmp_cards[15];
          cards[24] = tmp_cards[18];
          cards[25] = tmp_cards[21];
          cards[26] = tmp_cards[24];
          break;
        case "middle":
          cards[0] = tmp_cards[0];
          cards[1] = tmp_cards[3];
          cards[2] = tmp_cards[6];
          cards[3] = tmp_cards[9];
          cards[4] = tmp_cards[12];
          cards[5] = tmp_cards[15];
          cards[6] = tmp_cards[18];
          cards[7] = tmp_cards[21];
          cards[8] = tmp_cards[24];
          cards[9] = tmp_cards[2];
          cards[10] = tmp_cards[5];
          cards[11] = tmp_cards[8];
          cards[12] = tmp_cards[11];
          cards[13] = tmp_cards[14];
          cards[14] = tmp_cards[17];
          cards[15] = tmp_cards[20];
          cards[16] = tmp_cards[23];
          cards[17] = tmp_cards[26];
          cards[18] = tmp_cards[1];
          cards[19] = tmp_cards[4];
          cards[20] = tmp_cards[7];
          cards[21] = tmp_cards[10];
          cards[22] = tmp_cards[13];
          cards[23] = tmp_cards[16];
          cards[24] = tmp_cards[19];
          cards[25] = tmp_cards[22];
          cards[26] = tmp_cards[25];
          break;
        case "bottom":
          cards[0] = tmp_cards[0];
          cards[1] = tmp_cards[3];
          cards[2] = tmp_cards[6];
          cards[3] = tmp_cards[9];
          cards[4] = tmp_cards[12];
          cards[5] = tmp_cards[15];
          cards[6] = tmp_cards[18];
          cards[7] = tmp_cards[21];
          cards[8] = tmp_cards[24];
          cards[9] = tmp_cards[1];
          cards[10] = tmp_cards[4];
          cards[11] = tmp_cards[7];
          cards[12] = tmp_cards[10];
          cards[13] = tmp_cards[13];
          cards[14] = tmp_cards[16];
          cards[15] = tmp_cards[19];
          cards[16] = tmp_cards[22];
          cards[17] = tmp_cards[25];
          cards[18] = tmp_cards[2];
          cards[19] = tmp_cards[5];
          cards[20] = tmp_cards[8];
          cards[21] = tmp_cards[11];
          cards[22] = tmp_cards[14];
          cards[23] = tmp_cards[17];
          cards[24] = tmp_cards[20];
          cards[25] = tmp_cards[23];
          cards[26] = tmp_cards[26];
          break;
      }
      break;
    default:
      break;
  }
  return cards;
};

export default orderCards;
